version: '3'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: python:3.10
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "pip install flask flask-cors && python server.py"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./devices.db:/root/devices.db
